apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-4"
  annotations:
    argocd/app-name: my-quarkus-app-4-dev
    backstage.io/kubernetes-id: my-quarkus-app-4
    backstage.io/kubernetes-namespace: my-quarkus-app-4-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: my-org-to-backstage/quarkus-app-4
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-x94vs.x94vs.sandbox1644.opentlc.com/#https://github.com/my-org-to-backstage/quarkus-app-4?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-x94vs.x94vs.sandbox1644.opentlc.com/#https://github.com/my-org-to-backstage/quarkus-app-4?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/vinicius"
  providesApis:
    - "my-quarkus-app-4"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app-4"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/vinicius"
  definition:
    $text: ./openapi.yaml
